---
title: "Resultados Parciales - Elección a Gobernador de la Provincia de Córdoba (2019)"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(leaflet)
source("./r_scripts/data.R")
```

Inputs {.sidebar}
-------------------------------------

El siguiente dashboard muestra Resultados Parciales de las Elecciones a Gobernador para la Provincia de Córdoba en base a datos obtenidos del escrutinio paralelo realizado por Desarrollo Digital y Open Data Córdoba.

Hecho por [Patricio Del Boca](https://twitter.com/pdelboca) para [Open Data Córdoba](https://twitter.com/opendatacba).

Mayo 2019.

Column {data-width=300}
-------------------------------------
    
### Resultados Parciales
    
```{r}
knitr::kable(posiciones)
```

### Mesas Escrutadas
    
```{r}
mesas_escrutadas <- nrow(mesas)
valueBox(mesas_escrutadas, icon = "fa-pencil")
```

### Porcentaje Escrutado
    
```{r}
porc_mesas <- mesas_escrutadas / CANT_MESAS * 100
gauge(porc_mesas, min = 0, max=100, symbol = "%")
```
   

Column {data-width=600}
-------------------------------------
   
### Mapa de la Provincia

```{r}
m <- leaflet() %>% 
  addTiles() %>% 
  addMarkers(lng=circuitos_resultados$lng, lat=circuitos_resultados$lat)
m
```   